config/routes.rb
Okbrisbane::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :mypages, :only => ['index','edit','update']

  namespace :s do
    root :to => 'smarts#index'
    resources :member_managements, :only => [] do
      collection do
        get :term
        get :personal
      end
    end
  end

  match 'counters/batch', :via => :get

  match 'users/member_managements/sign_in', :via => :get, :as => :user_sign_in
  match 'users/member_managements/sign_up', :via => :get, :as => :user_sign_up
  match 'users/member_managements/sign_out', :via => :get, :as => :user_sign_out
  match 'users/member_managements/term', :via=>:get, :as => :termsofservice
  match 'users/member_managements/personal', :via=>:get, :as => :termsofpersonal
  match 'users/member_managements/agreememnt_required', :via=>:get, :as => :agreement
  match 'users/member_managements/agreed', :via=>:get, :as => :agreed
  match 'users/member_managements/inactive_signup', :via=>:get, :as => :user_inactive_signup
  match 'users/member_managements/sending_reset_password_instructions', :via=>:get, :as => :user_sending_reset_password_instructions
  match 'users/member_managements/after_reset_password', :via=>:get, :as => :user_after_reset_passwod
  match 'users/member_managements/after_confirmation', :via=>:get, :as => :user_after_confirmation
  match 'users/member_managements/after_resending_confirmation_instructions', :via=>:get, :as => :user_after_resending_confirmation_instructions

  namespace :users do
    resources :member_managements, :only => ["index","new","create"]
  end
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions", :confirmations => "users/confirmations", :passwords => "users/passwords", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :images, :only => ["create","destroy", "index"]
  resources :attachments, :only => ["create","destroy", "index"]

  resources :sponsors, :only => [] do
    collection do
      get :show
      get :show_ok
      get :thank_you
    end
  end

  resource :banners, :only => [] do
    collection do
      post :show_single_banner
      post :show_multi_banner
    end
  end

  resources :contacts, :only => ["index","create","new"]

  resources :homes, :only => ["index"] do
    collection do
      post :current_weather
      post :current_rate
      post :top_feed
      post :admin_notice
      get  :topic_feed
    end
  end

  resources :business_clients do
    collection do
      post :select_category
      get :query
      post :search
    end
  end

  resources :post_searches, :only => ["index","create","edit","update"]

  resources :okboards, :only => ['index'] do
    collection do
      get :mypage
      get :yellowpage
      post :more
      post :post_admin_notice
      get :view
      get :write
      post :upload_image
      post :upload_attachment
      post :get_image
      post :get_attachment
      delete :delete_image
      delete :delete_attachment
      post :likes
      post :dislikes
      post :abuses
      post :next_post
      post :prev_post
    end
  end

  resources :jobs, :only => ["new","create"]
  resources :buy_and_sells, :only => ["new","create"]
  resources :well_beings, :only => ["new","create"]
  resources :accommodations, :only => ["new","create"]
  resources :laws, :only => ["new","create"]
  resources :taxes, :only => ["new","create"]

  match 'comments/:id/likes' => "comments#likes", :via=>:post, :as => :comment_like
  match 'comments/:id/dislikes' => "comments#dislikes", :via=>:post, :as => :comment_dislike
  match 'comments/:id/abuses' => "comments#abuses", :via=>:post, :as => :comment_abuse
  match 'comments/:id/new' => "comments#new", :via=>:get, :as => :comment_new
  match 'comments/:id/reply' => "comments#reply", :via=>:post, :as => :comment_reply
  resources :comments, :only => ['index',"create"] do
    collection do
      post :dislike
      post :abuse
      post :post_for
    end
  end

  root :to => 'homes#index'

end

app/controllers/s/smarts_controller.rb
class S::SmartsController < S::SmartApplicationController
   
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  def term
    respond_to do |format|
      format.html # index.html.erb
    end
  end

end

app/views/s/smarts/_content.html.erb
<i class="icon-spin icon-spinner"></i>
<hr>
<%= _mobile_link_to_with_icon(t("more"),"\#page-#{key}","button","","","icon-cogs","#{key}",%|data-inline="true"|)%>

app/views/s/smarts/_signin.html.erb
<h3><%=t("Signin")%></h3>
<div style="padding:10px 20px;">
<%= form_for("user", :url => user_session_path, :html => { :class => "header-signin-form"}) do |f| %>
		<span class="add-on"><i class="icon-envelope"></i>&nbsp;<%=t("email")%></span><%= f.email_field :email, :class => "" %>
	<span class="add-on"><i class="icon-key"></i>&nbsp;<%=t("password")%></span><%= f.password_field :password, :class => "" %>
<fieldset data-role="controlgroup" data-type="horizontal">
<label class="checkbox" data-mini="true"> <%= f.check_box :remember_me %><%= t(:remember_me_short) %> </label>
</fieldset>
<%= _mobile_link_to_with_icon(t(:signin), "#", "button", "", "", "icon-signin", "header-signin", %|data-theme="b"| ) %>
<%= link_to(t("findid_short"),"#",:class=>"")%>
<%= link_to(t("findpassword"),"#",:class=>"")%>
<%= _document_on("click","\#header-signin",%Q|function(){
	$.mobile.loading( 'show', {
		text: '#{t("loading")}',
		textVisible: true,
		theme: 'c',
		html: ""
	});
	//$(".header-signin-form").submit();
	return false;
	}
|)
%>
<% end %>
</div>

app/views/s/smarts/index.html.erb
<div data-role="page" data-theme="c">

	<div data-role="header">

		<div class="ui-grid-a">
			<div class="ui-block-a">
				<% logo = BusinessClient.okbrisbane?.logo_for(Webcom::Browser::DEVISE_PHONE) %>
				<% if logo.present? %>
				<%= link_to image_tag(logo.original_image, :class => ""), s_root_path(:locale => 'ko' ) %>
				<% else %>
				<%= link_to image_tag("http://placehold.it/150x50", :class => ""), s_root_path(:locale => 'ko' ) %>
				<% end %>
			</div>
			<div class="ui-block-b">
				<h3><%= t("okpage_top_description")%></h3>
				<% if current_user %>
				<p><%=t("welcome_message")%>&nbsp;<%= show_user %></p>
				<% end%>
			</div>
		</div>
		<div data-role="navbar">
			<ul>
				<% if !current_user %>
				<li>
					<%= _mobile_link_to_with_icon(t(:signin), "#popupSignin", "button", "", "","icon-signin","",%Q|data-rel="popup" data-transition="slidedown"|) %>
				</li>
				<li>
					<%= _mobile_link_to_with_icon(t(:signup), "#", "button", "", "","icon-ok","") %>
				</li>
				<li>
					<%= _mobile_link_to_with_icon(t(:write_new), "#", "button", "", "","icon-pencil","") %>
				</li>
				<% else %>
				<li>
				<%= _mobile_link_to_with_icon(t(:mypage), "#", "button", "", "", "icon-user","") %>
				</li>
				<li>
				<%= _mobile_link_to_with_icon(t(:signout), "#", "button", "", "", "icon-signout", "", %Q|data-merhod="delete"|) %>
				</li>
				<% end %>
			</ul>
		</div>
		<%= mobile_header_banner(1)%>
		<div data-role="popup" id="popupSignin" data-theme="c" class="ui-corner-all">
			<a href="#" data-rel="back" data-role="button" data-theme="a" data-icon="delete" data-iconpos="notext" class="ui-btn-right">Close</a>
			<%= render :partial => "s/smarts/signin"%>
		</div>
	</div>
	<div data-role="content">
		<div data-role="collapsible-set">
			<% Style.mobile_feed.each do |k,v| %>
			<div data-role="collapsible" class="content-menu-<%=k%>">
				<h3 id="feed-<%=k%>"><i class="<%= v[:feed][:icon]%>"></i>&nbsp;<%= t(v[:feed][:text])%></h3>
				<%= render :partial => "s/smarts/content", :locals => {:key => k}%>
			</div>
			<%= _document_pageinit(%Q|$(".content-menu-#{k}").bind("expand", function(event, ui) { console.log("hello"); }
			);|)%>
			<% end %>

		</div>
	</div>
	<div data-role="footer" >
		<footer>
			<h5>Copyright &copy; <%= Common.current_time.year %> <%= Okvalue::FOOTER_TEXT1%>
			<br>
			<%= Okvalue::FOOTER_TEXT2 %>
			<br>
			<div class="">
				<%= link_to(t(:termsofservice), term_s_member_managements_path, :class => "footer_text")%>
				<%= link_to(t(:termsofpersonalinfo), personal_s_member_managements_path, :class => "footer_text")%>
				<%= link_to(t(:banner_contact), "#", :class => "footer_text")%>
				<%= link_to(t(:general_contact), "#", :class => "footer_text")%>
			</div>
			<p class="developer pull-left">
				<small>Developed by <%= link_to("Kenichi Takemura", "http://www.facebook.com/kenichi.takemura") %></small>
			</p></h5>
		</footer>

	</div>
</div>