config/routes.rb
Okbrisbane::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :mypages, :only => ['index','edit','update']

  namespace :s do
    root :to => 'smarts#index'
    resources :member_managements, :only => [] do
      collection do
        get :term
        get :personal
      end
    end
  end

  match 'counters/batch', :via => :get

  match 'users/member_managements/sign_in', :via => :get, :as => :user_sign_in
  match 'users/member_managements/sign_up', :via => :get, :as => :user_sign_up
  match 'users/member_managements/sign_out', :via => :get, :as => :user_sign_out
  match 'users/member_managements/term', :via=>:get, :as => :termsofservice
  match 'users/member_managements/personal', :via=>:get, :as => :termsofpersonal
  match 'users/member_managements/agreememnt_required', :via=>:get, :as => :agreement
  match 'users/member_managements/agreed', :via=>:get, :as => :agreed
  match 'users/member_managements/inactive_signup', :via=>:get, :as => :user_inactive_signup
  match 'users/member_managements/sending_reset_password_instructions', :via=>:get, :as => :user_sending_reset_password_instructions
  match 'users/member_managements/after_reset_password', :via=>:get, :as => :user_after_reset_passwod
  match 'users/member_managements/after_confirmation', :via=>:get, :as => :user_after_confirmation
  match 'users/member_managements/after_resending_confirmation_instructions', :via=>:get, :as => :user_after_resending_confirmation_instructions

  namespace :users do
    resources :member_managements, :only => ["index","new","create"]
  end
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions", :confirmations => "users/confirmations", :passwords => "users/passwords", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :images, :only => ["create","destroy", "index"]
  resources :attachments, :only => ["create","destroy", "index"]

  resources :sponsors, :only => [] do
    collection do
      get :show
      get :show_ok
      get :thank_you
    end
  end

  resource :banners, :only => [] do
    collection do
      post :show_single_banner
      post :show_multi_banner
    end
  end

  resources :contacts, :only => ["index","create","new"]

  resources :homes, :only => ["index"] do
    collection do
      post :current_weather
      post :current_rate
      post :top_feed
      post :admin_notice
      get  :topic_feed
    end
  end

  resources :business_clients do
    collection do
      post :select_category
      get :query
      post :search
    end
  end

  resources :post_searches, :only => ["index","create","edit","update"]

  resources :okboards, :only => ['index'] do
    collection do
      get :mypage
      get :yellowpage
      post :more
      post :post_admin_notice
      get :view
      get :write
      post :upload_image
      post :upload_attachment
      post :get_image
      post :get_attachment
      delete :delete_image
      delete :delete_attachment
      post :likes
      post :dislikes
      post :abuses
      post :next_post
      post :prev_post
    end
  end

  resources :jobs, :only => ["new","create"]
  resources :buy_and_sells, :only => ["new","create"]
  resources :well_beings, :only => ["new","create"]
  resources :accommodations, :only => ["new","create"]
  resources :laws, :only => ["new","create"]
  resources :taxes, :only => ["new","create"]

  match 'comments/:id/likes' => "comments#likes", :via=>:post, :as => :comment_like
  match 'comments/:id/dislikes' => "comments#dislikes", :via=>:post, :as => :comment_dislike
  match 'comments/:id/abuses' => "comments#abuses", :via=>:post, :as => :comment_abuse
  match 'comments/:id/new' => "comments#new", :via=>:get, :as => :comment_new
  match 'comments/:id/reply' => "comments#reply", :via=>:post, :as => :comment_reply
  resources :comments, :only => ['index',"create"] do
    collection do
      post :dislike
      post :abuse
      post :post_for
    end
  end

  root :to => 'homes#index'

end

app/models/member_management.rb
class MemberManagement < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/s/member_managements_controller.rb
class S::MemberManagementsController < S::SmartApplicationController

  def term
    respond_to do |format|
      format.html
    end
  end

  def personal
    respond_to do |format|
      format.html
    end
  end
  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

  before_filter :okpage
  
  def okpage
    @okpage = :p_signin
  end

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    logger.debug("after_resending_confirmation_instructions_path_for")
    user_after_resending_confirmation_instructions_path
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    logger.debug("after_confirmation_path_for")
    user_after_confirmation_path
  end

end

app/controllers/users/member_managements_controller.rb
class Users::MemberManagementsController < OkController

  before_filter :page_p_signup, :only => ["sign_up","term","personal","create","inactive_signup"]
  before_filter :page_p_signin, :only => ["sing_in","sending_reset_password_instructions","after_reset_password","after_confirmation","after_resending_confirmation_instructions","agreememnt_required"]
  def page_p_signup
    @okpage = :p_signup
  end

  def page_p_signin
    @okpage = :p_signin
  end

  def sign_in
    session[:signin_menu] = :singin
    redirect_to new_user_session_path
  end

  def sign_out
    @okpage = :p_signout
    respond_to do |format|
      format.html # sign_out.html.erb
    end
  end

  def sign_up
    @users_member_management = MemberManagement.new
    respond_to do |format|
      format.html # sign_up.html.erb
      format.json { render :json => @users_member_management }
    end
  end

  def inactive_signup
    @email = params[:email]
    respond_to do |format|
      format.html
    end
  end

  def sending_reset_password_instructions
    @email = params[:email]
    respond_to do |format|
      format.html { render :template => "member_managements/reset_password" }
      format.json { render :json => @email }
    end
  end
  
  def after_reset_password 
    respond_to do |format|
      format.html
    end
  end
  
  def after_confirmation
    respond_to do |format|
      format.html
    end
  end
  
  def after_resending_confirmation_instructions
    respond_to do |format|
      format.html
    end
  end

  def term
    respond_to do |format|
      format.html # term.html.erb
    end
  end

  def personal
    respond_to do |format|
      format.html # personal.html.erb
    end
  end
  
  def agreememnt_required
    @users_member_management = MemberManagement.new
    respond_to do |format|
      format.html
    end
  end

  def create
    session[:agreed] = true
    redirect_to new_user_registration_path
  end
  
  def agreed
    logger.info("User agreed. current_user: #{current_user}")
    redirect_to new_user_registration_path if !current_user
    current_user.agree
    redirect_to after_sign_in_path_for(current_user)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    logger.info("OmniauthCallback facebook #{request.env["omniauth.auth"]}")
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.present? && @user.persisted?
      logger.info("User signed in via Facebook")
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      #redirect_to new_flyer_registration_url
      redirect_to root_path
    end
  end

  def google_oauth2
    logger.info("OmniauthCallback google_oauth2 #{request.env["omniauth.auth"]}")
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
    if @user.present? && @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      #redirect_to new_flyer_registration_url
      redirect_to root_path
    end
  end

  def naver
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    logger.info("OmniauthCallback naver #{request.env["omniauth.auth"]}")
    @user = User.find_for_naver_oauth(request.env["omniauth.auth"], current_user)

  end

  # Override
  def failure
    logger.error("OmniauthCallbacksController failure_message: #{failure_message}")
    set_flash_message :alert, :failure, :kind => failed_strategy.name.to_s.humanize, :reason => failure_message
    #flash[:alert] = I18n.t "devise.omniauth_callbacks.flyer.failure", :kind => failed_strategy.name.to_s.humanize, :reason => failure_message
    redirect_to after_omniauth_failure_path_for(resource_name)
  end

  def after_omniauth_failure_path_for(scope)
    logger.warn("after_omniauth_failure_path_for #{scope}")
    root_path
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  
  before_filter :okpage
  
  def okpage
    @okpage = :p_signin
  end
  
  def after_sending_reset_password_instructions_path_for(resource_name)
     logger.debug("after_sending_reset_password_instructions_path_for")
     user_sending_reset_password_instructions_path(:email => resource.email)
  end
  
  def after_sign_in_path_for(resource)
    logger.debug("after_sign_in_path_for")
    user_after_reset_passwod_path
  end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
  before_filter :okpage
  
  def okpage
    @okpage = :p_signup
  end
  
  def new
    if session[:agreed]
      super
    else
      redirect_to member_managements_sign_up_path
    end
  end
  
  def create
    resource_params[:agreed_on] = Common.current_time
    resource_params[:provider] = User::PROVIDERS[:okbrisbane]
    # This is dummy
    resource_params[:uid] = Common.unique_token
    super
  end
  
  # If the account that is registered is confirmable and not active yet, you have to override after_inactive_sign_up_path_for method.
  def after_inactive_sign_up_path_for(resource)
    logger.debug("after_inactive_sign_up_path_for")
    user_inactive_signup_path(:email => resource.email)
  end
   
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  before_filter :okpage
  
  def okpage
    @okpage = :p_signin
  end
  
  def self.force_sign_out(resource)
    sign_out(resource)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def self.termsofservice
    f = File.open("#{Rails.root}/config/locales/termsofservice." + "#{I18n.locale}", "r:utf-8")
    term = f.read
    f.close
    term
  end
  def self.termofpersonalinfomation
    t = File.open("#{Rails.root}/config/locales/termofpersonalinfomation." + "#{I18n.locale}", "r:utf-8")
    term = t.read
    t.close
    term.html_safe
  end
end

app/views/users/member_managements/after_confirmation.html.erb
<%= render :partial => "devise/shared/header" %>

<div id="_title">
	<div class="page-header">
		<h1> <%= t(:Signup)%> </h1>
		<h3 class="text-info">
			<%= t("Signup_okpage_top_description".to_sym) %>
		</h3>
	</div>
</div>
<%= image_tag("#{I18n.locale}/Signup/img_process03_on.gif")%>
<hr>
<%= show_notice %>
<%= show_alert %>

<div id="_main">

<div class="after_confirmation_banner">
	<%= single_body_banner(6) %>
</div>
</div>
<%= render :partial => "devise/shared/footer" %>
<%= active_menu("_signup") %>

app/views/users/member_managements/after_resending_confirmation_instructions.html.erb
<%= render :partial => "devise/shared/header" %>
<div id="_title">
	<div class="page-header">
		<h1> <%= t(:findid)%> </h1>
		<p>
			<%= t("#{Style.page(@okpage)}_okpage_top_description".to_sym) %>
		</p>
	</div>
</div>
<%= show_notice %>
<%= show_alert %>
<div id="_main">
	<%= image_tag("#{I18n.locale}/common/img_sendmail_ok.gif")%>
</div>
<%= render :partial => "devise/shared/footer" %>
<%= active_menu("_findid") %>

app/views/users/member_managements/after_reset_password.html.erb
<%= render :partial => "devise/shared/header" %>

<div id="_title">
	<div class="page-header">
		<h1> <%= t(:forgot_your_password)%> </h1>
		<p>
			<%= t("#{Style.page(@okpage)}_okpage_top_description".to_sym) %>
		</p>
	</div>
</div>
<%= show_notice %>
<%= show_alert %>
<div id="_main">
</div>
<%= render :partial => "devise/shared/footer" %>
<%= active_menu("_findpassword") %>

app/views/users/member_managements/agreememnt_required.html.erb
<%= render :partial => "devise/shared/header" %>
<div id="_title">
	<div class="page-header">
		<h1> <%= t(Style.page(@okpage))%> </h1>
		<p>
			<%= t("#{Style.page(@okpage)}_okpage_top_description".to_sym) %>
		</p>
	</div>
</div>

<div class="alert alert-info">
	<%= t(:agreement_required)%>
</div>
<div id="_main">
	<div class="signup_form">
		<h4 class="text-info"> <%= t("termofservice")%> </h4>
		<div style="width:100%;height:500px;overflow:auto;">
			<blockquote>
				<%= raw(UsersHelper.termsofservice) %>
			</blockquote>
		</div>
		<br>
		<h4 class="text-info"> <%= t("termofpersonalinfomation")%> </h4>
		<div style="width:100%;height:500px;overflow:auto;">
			<blockquote>
				<%= raw(UsersHelper.termofpersonalinfomation) %>
			</blockquote>
		</div>
		<br>
		<div class="actions">
			<%= link_to(image_tag("#{I18n.locale}/Signup/agreement.jpg"), agreed_path, :class => "") %>
		</div>
	</div>
</div>
<%= render :partial => "devise/shared/footer" %>
<%= active_menu("_signin") %>

app/views/users/member_managements/inactive_signup.html.erb
<%= render :partial => "devise/shared/header" %>
<div id="_title">
	<div class="page-header">
		<h1> <%= t(Style.page(@okpage))%> </h1>
		<h3 class="text-info">
			<%= t("#{Style.page(@okpage)}_okpage_top_description".to_sym) %>
		</h3>
	</div>
</div>
<%= image_tag("#{I18n.locale}/Signup/img_process02_on.gif")%>
<hr>
<%= show_notice %>
<%= show_alert %>
<div id="_main">
<%= image_tag("#{I18n.locale}/common/img_sendmail_ok.gif")%>
</div>
<%= render :partial => "devise/shared/footer" %>
<%= active_menu("_signup") %>

app/views/users/member_managements/personal.html.erb
<%= render :partial => "devise/shared/header" %>


<div id="_title">
	<div class="page-header">
		<h1> <%= t(:termsofpersonalinfo)%> </h1>
		<p>
			<%= t("#{Style.page(@okpage)}_okpage_top_description".to_sym) %>
		</p>
	</div>
</div>
		<div class="alert alert-info">
		<%= t(:termofpersonalinfomation)%>
	</div>
	<div style="width:100%;height:800px;overflow:auto;">
	<blockquote>
		<%= raw(UsersHelper.termofpersonalinfomation) %>
	</blockquote>
	</div>
	<br>                           
<%= link_to_with_icon(t(:up), "#_title", "btn btn-mini", "", "icon-arrow-up")%>

</div>
<%= render :partial => "devise/shared/footer" %>
<%= active_menu("_termsofpersonalinfo") %>

app/views/users/member_managements/reset_password.html.erb
<%= render :partial => "devise/shared/header" %>

<div id="_title">
	<div class="page-header">
		<h1> <%= t(:forgot_your_password)%> </h1>
		<p>
			<%= t("#{Style.page(@okpage)}_okpage_top_description".to_sym) %>
		</p>
	</div>
</div>

<%= show_notice %>
<%= show_alert %>

<div id="_main">
	<%= image_tag("#{I18n.locale}/common/img_sendmail_ok.gif")%>
</div>
<%= render :partial => "devise/shared/footer" %>
<%= active_menu("_signin") %>

app/views/users/member_managements/sign_out.html.erb
<%= render :partial => "devise/shared/header" %>

<%= show_notice %>
<%= show_alert %>

<%= single_body_banner(6) %>
</div>
<%= render :partial => "devise/shared/footer" %>
<%= active_menu("_signin") %>

app/views/users/member_managements/sign_up.html.erb
<%= render :partial => "devise/shared/header" %>
<div id="_title">
	<div class="page-header">
		<h1> <%= t(Style.page(@okpage))%> </h1>
		<h3 class="text-info">
			<%= t("#{Style.page(@okpage)}_okpage_top_description".to_sym) %>
		</h3>
		<hh4 class="text-info">
			<%= t("#{Style.page(@okpage)}_okpage_top_description1".to_sym) %>
		</h4>
	</div>
</div>
<%= image_tag("#{I18n.locale}/Signup/img_process01_on.gif")%>
<div id="_main">
	<div class="signup_form">
	<h4 class="text-info">
		<%= t("termofservice")%>
	</h4>
	<div style="width:100%;height:500px;overflow:auto;">
	<blockquote>
		<%= raw(UsersHelper.termsofservice) %>
	</blockquote>
	</div>
	<br>
	<h4 class="text-info">
		<%= t("termofpersonalinfomation")%>
	</h4>
	<div style="width:100%;height:500px;overflow:auto;">
	<blockquote>
		<%= raw(UsersHelper.termofpersonalinfomation) %>
	</blockquote>
	</div>
	<br>
    <label class="checkbox" >
    	<input type="checkbox" value="" id="_agree"><%= t(:agree) %>
    </label>
    <div class="unchecked" style="display:none">
    	<div class="alert alert-info"><h4><%=t(:agree_is_required)%></h4></div>
    </div>
	<%= form_for(@users_member_management, :url => users_member_managements_path) do |f| %>
	<div class="actions">
		<%= image_submit_tag("#{I18n.locale}/Signup/agreement.jpg", :class => "", :id => "_next") %>
	</div>
	<% end %>
	</div>
</div>
<%= render :partial => "devise/shared/footer" %>
<%= active_menu("_signup") %>
<%= _script_document_ready(%Q|
$('\#_next').click(function() {if ($('\#_agree').is(':checked')) {} else {$('div.unchecked').show('slow');return false;}});|) %>

app/views/users/member_managements/term.html.erb
<%= render :partial => "devise/shared/header" %>

<div id="_title">
	<div class="page-header">
		<h1> <%= t(:termsofservice)%> </h1>
		<p>
			<%= t("#{Style.page(@okpage)}_okpage_top_description".to_sym) %>
		</p>
	</div>
</div>

<div class="alert alert-info">
		<%= t(:termofservice)%>
	</div>
	<div style="width:100%;height:800px;overflow:auto;">
	<blockquote>
		<%= raw(UsersHelper.termsofservice) %>
	</blockquote>
	</div>
	<br>
<%= link_to_with_icon(t(:up), "#_title", "btn btn-mini", "", "icon-arrow-up")%>

<%= render :partial => "devise/shared/footer" %>
<%= active_menu("_termsofservice") %>