config/routes.rb
Okbrisbane::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :mypages, :only => ['index','edit','update']

  namespace :s do
    root :to => 'smarts#index'
    resources :member_managements, :only => [] do
      collection do
        get :term
        get :personal
      end
    end
  end

  match 'counters/batch', :via => :get

  match 'users/member_managements/sign_in', :via => :get, :as => :user_sign_in
  match 'users/member_managements/sign_up', :via => :get, :as => :user_sign_up
  match 'users/member_managements/sign_out', :via => :get, :as => :user_sign_out
  match 'users/member_managements/term', :via=>:get, :as => :termsofservice
  match 'users/member_managements/personal', :via=>:get, :as => :termsofpersonal
  match 'users/member_managements/agreememnt_required', :via=>:get, :as => :agreement
  match 'users/member_managements/agreed', :via=>:get, :as => :agreed
  match 'users/member_managements/inactive_signup', :via=>:get, :as => :user_inactive_signup
  match 'users/member_managements/sending_reset_password_instructions', :via=>:get, :as => :user_sending_reset_password_instructions
  match 'users/member_managements/after_reset_password', :via=>:get, :as => :user_after_reset_passwod
  match 'users/member_managements/after_confirmation', :via=>:get, :as => :user_after_confirmation
  match 'users/member_managements/after_resending_confirmation_instructions', :via=>:get, :as => :user_after_resending_confirmation_instructions

  namespace :users do
    resources :member_managements, :only => ["index","new","create"]
  end
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions", :confirmations => "users/confirmations", :passwords => "users/passwords", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :images, :only => ["create","destroy", "index"]
  resources :attachments, :only => ["create","destroy", "index"]

  resources :sponsors, :only => [] do
    collection do
      get :show
      get :show_ok
      get :thank_you
    end
  end

  resource :banners, :only => [] do
    collection do
      post :show_single_banner
      post :show_multi_banner
    end
  end

  resources :contacts, :only => ["index","create","new"]

  resources :homes, :only => ["index"] do
    collection do
      post :current_weather
      post :current_rate
      post :top_feed
      post :admin_notice
      get  :topic_feed
    end
  end

  resources :business_clients do
    collection do
      post :select_category
      get :query
      post :search
    end
  end

  resources :post_searches, :only => ["index","create","edit","update"]

  resources :okboards, :only => ['index'] do
    collection do
      get :mypage
      get :yellowpage
      post :more
      post :post_admin_notice
      get :view
      get :write
      post :upload_image
      post :upload_attachment
      post :get_image
      post :get_attachment
      delete :delete_image
      delete :delete_attachment
      post :likes
      post :dislikes
      post :abuses
      post :next_post
      post :prev_post
    end
  end

  resources :jobs, :only => ["new","create"]
  resources :buy_and_sells, :only => ["new","create"]
  resources :well_beings, :only => ["new","create"]
  resources :accommodations, :only => ["new","create"]
  resources :laws, :only => ["new","create"]
  resources :taxes, :only => ["new","create"]

  match 'comments/:id/likes' => "comments#likes", :via=>:post, :as => :comment_like
  match 'comments/:id/dislikes' => "comments#dislikes", :via=>:post, :as => :comment_dislike
  match 'comments/:id/abuses' => "comments#abuses", :via=>:post, :as => :comment_abuse
  match 'comments/:id/new' => "comments#new", :via=>:get, :as => :comment_new
  match 'comments/:id/reply' => "comments#reply", :via=>:post, :as => :comment_reply
  resources :comments, :only => ['index',"create"] do
    collection do
      post :dislike
      post :abuse
      post :post_for
    end
  end

  root :to => 'homes#index'

end

app/views/okboards/shared/upload/_attachment.html.erb
<div class="attachment">
<%= form_for(@attachment, :html => { :multipart => true, :id => "attachment-form" }, :remote => true) do |attachment_form| %>
<fieldset>
	<%= attachment_form.hidden_field :write_at, :id => "write_at" %>
	<%= attachment_form.label "#{t("attachment") + t("add")}" %>
	<%= attachment_form.file_field :attachment, :id => "upload_attachment" %>
	<span class="help-inline"><%= t("max_size", :size => number_to_human_size(Okvalue::MAX_POST_IMAGE_SIZE))%></span>
	<br>
	<%= link_to_with_icon("", "#", "btn btn-info", "", "icon-cloud-upload icon-2x","upload_attachment_submit") %>
</fieldset>
<% end %>
<%= _script(%Q|$('\#upload_attachment_submit').click(function(){
	if($('\#upload_attachment').val() != "") {
		$('\#upload_attachment_status').html("#{escape_javascript(image_tag("common/ajax_loading.gif"))}");
		$('\#attachment-form').submit();
		}
	return false;
})|)%>
<div id="upload_attachment_status"></div>
<div id="upload_attachment_area"></div>
</div>
<%= _script_document_ready(%Q|
	$('\#upload_attachment_status').html("#{escape_javascript(image_tag("common/ajax_loading.gif"))}");
	#{Ajax.get(attachments_path,%Q|write_at: $('\#write_at').val()|)}
|) %>

app/views/okboards/shared/upload/_attachment_box.html.erb
<% if @attachments.present? %>
<ul class="thumbnails">
<% @attachments.each do |attachment| %>
	<li class="span3 pull-left">
		<div class="thumbnail">
		<%= image_tag("common/Icon-Document03-Blue.png", :class => "image-resize50_50", :title => "#{attachment.avatar_file_name}") %>
		<%= link_to(t('x'), attachment_path(attachment), :class => "image-delete pull-right", :remote => true, :method => :delete, :data => { :confirm => t('confirm_delete') }) %> 
		<p><%= attachment.filename%></p>
		<p><%= attachment.filesize%>&nbsp;byte</p>
	</div>
	</li>
<% end %>
</ul>
<% end %>

app/views/okboards/shared/upload/_image.html.erb
<div class="image">
<%= form_for(@image, :html => { :multipart => true, :id => "image-form" }, :remote => true) do |image_form| %>
<fieldset>
	<%= image_form.hidden_field :write_at, :id => "write_at" %>
	<%= image_form.label :image, "#{t("image") + t("upload")}" %>
	<span class="help-block"><%= t("post_image_upload_description") %></span>
	<%= image_form.file_field :image, :id => "upload_image" %>
	<span class="help-inline"><%= t("max_size", :size => number_to_human_size(Okvalue::MAX_POST_IMAGE_SIZE))%></span>
	<br>
	<%= image_form.text_area :something, :placeholder => t("write_something"), :class => "text_area", :id => "upload_something", :style => "margin-top:5px", :rows => "3" %>
	<br>
	<%= link_to_with_icon_with_id("", "#", "btn btn-info", "", "upload_image_submit", "icon-cloud-upload icon-2x","") %>
</fieldset>
<% end %>
<%= _script(%Q|$('\#upload_image_submit').click(function(){
	if($('\#upload_image').val() != "") {
		$('\#upload_image_status').html("#{escape_javascript(image_tag("common/ajax_loading.gif"))}");
		$('\#image-form').submit();
	}
	return false;
}
)|)%>
<div id="upload_image_status"></div>
<div id="upload_image_area"></div>
</div>
<%= _script_document_ready(%Q|
	$('\#upload_image_status').html("#{escape_javascript(image_tag("common/ajax_loading.gif"))}");
	#{Ajax.get(images_path,%Q|write_at: $('\#write_at').val()|)}
|) %>

app/views/okboards/shared/upload/_image_box.html.erb
<% if @images.present? %>
<ul class="thumbnails">
<% @images.each do |image| %>
	<li class="span3 pull-left">
		<div class="thumbnail">
		<%= image_tag(image.thumb_image, :title => "#{image.avatar_file_name}") %>
		<%= link_to_with_icon_remote_with_confirm("", image_path(image), "image-delete pull-right", "", "icon-remove-circle", "", "delete", t('confirm_delete')) %> 
			<p><%= image.something%></p>
			<p><%= image.filename%></p>
			<p><%= image.filesize%>&nbsp;byte</p>
	</div>
	</li>
<% end %>
</ul>
<% end %>