config/routes.rb
Okbrisbane::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :mypages, :only => ['index','edit','update']

  namespace :s do
    root :to => 'smarts#index'
    resources :member_managements, :only => [] do
      collection do
        get :term
        get :personal
      end
    end
  end

  match 'counters/batch', :via => :get

  match 'users/member_managements/sign_in', :via => :get, :as => :user_sign_in
  match 'users/member_managements/sign_up', :via => :get, :as => :user_sign_up
  match 'users/member_managements/sign_out', :via => :get, :as => :user_sign_out
  match 'users/member_managements/term', :via=>:get, :as => :termsofservice
  match 'users/member_managements/personal', :via=>:get, :as => :termsofpersonal
  match 'users/member_managements/agreememnt_required', :via=>:get, :as => :agreement
  match 'users/member_managements/agreed', :via=>:get, :as => :agreed
  match 'users/member_managements/inactive_signup', :via=>:get, :as => :user_inactive_signup
  match 'users/member_managements/sending_reset_password_instructions', :via=>:get, :as => :user_sending_reset_password_instructions
  match 'users/member_managements/after_reset_password', :via=>:get, :as => :user_after_reset_passwod
  match 'users/member_managements/after_confirmation', :via=>:get, :as => :user_after_confirmation
  match 'users/member_managements/after_resending_confirmation_instructions', :via=>:get, :as => :user_after_resending_confirmation_instructions

  namespace :users do
    resources :member_managements, :only => ["index","new","create"]
  end
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions", :confirmations => "users/confirmations", :passwords => "users/passwords", :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :images, :only => ["create","destroy", "index"]
  resources :attachments, :only => ["create","destroy", "index"]

  resources :sponsors, :only => [] do
    collection do
      get :show
      get :show_ok
      get :thank_you
    end
  end

  resource :banners, :only => [] do
    collection do
      post :show_single_banner
      post :show_multi_banner
    end
  end

  resources :contacts, :only => ["index","create","new"]

  resources :homes, :only => ["index"] do
    collection do
      post :current_weather
      post :current_rate
      post :top_feed
      post :admin_notice
      get  :topic_feed
    end
  end

  resources :business_clients do
    collection do
      post :select_category
      get :query
      post :search
    end
  end

  resources :post_searches, :only => ["index","create","edit","update"]

  resources :okboards, :only => ['index'] do
    collection do
      get :mypage
      get :yellowpage
      post :more
      post :post_admin_notice
      get :view
      get :write
      post :upload_image
      post :upload_attachment
      post :get_image
      post :get_attachment
      delete :delete_image
      delete :delete_attachment
      post :likes
      post :dislikes
      post :abuses
      post :next_post
      post :prev_post
    end
  end

  resources :jobs, :only => ["new","create"]
  resources :buy_and_sells, :only => ["new","create"]
  resources :well_beings, :only => ["new","create"]
  resources :accommodations, :only => ["new","create"]
  resources :laws, :only => ["new","create"]
  resources :taxes, :only => ["new","create"]

  match 'comments/:id/likes' => "comments#likes", :via=>:post, :as => :comment_like
  match 'comments/:id/dislikes' => "comments#dislikes", :via=>:post, :as => :comment_dislike
  match 'comments/:id/abuses' => "comments#abuses", :via=>:post, :as => :comment_abuse
  match 'comments/:id/new' => "comments#new", :via=>:get, :as => :comment_new
  match 'comments/:id/reply' => "comments#reply", :via=>:post, :as => :comment_reply
  resources :comments, :only => ['index',"create"] do
    collection do
      post :dislike
      post :abuse
      post :post_for
    end
  end

  root :to => 'homes#index'

end

app/models/home.rb
class Home < ActiveRecord::Base
  has_many :business_profile_image, :as => :attached, :dependent => :destroy, :class_name => 'BusinessProfileImage'
end

app/controllers/homes_controller.rb
class HomesController < OkController
  
  def collectImageFeed(category)
    limit = TopFeedList::TOP_FEED_LIMIT_CATE[category].presence || TopFeedList::TOP_FEED_LIMIT
    image_list = TopFeedList.feed_with_image(category, TopFeedList::IMAGE_FEED_LIMIT) 
    list = TopFeedList.feed_nomatter_image_except(category, collect_image_id(image_list), limit)
    return list,image_list
  end
  
  def collectTextFeed(category)
    limit = TopFeedList::TOP_FEED_LIMIT_CATE[category].presence || TopFeedList::TOP_FEED_LIMIT
    TopFeedList.feed_nomatter_image(category, limit)
  end
  
  def pick_feed
    Style.text_feed.each do |k,v|
      @feed_lists[category] = collectTextFeed(k)
    end
    Style.image_feed.each do |k,v|
      @feed_lists[category],@image_feed_lists[category] = collectImageFeed(k)
    end
  end

  def index
    if !top_page_ajaxable?
      @feed_lists = Hash.new
      @image_feed_lists = Hash.new
      pick_feed
    else
      @feed_lists = Hash.new
      @image_feed_lists = Hash.new
      Style.text_feed.each do |k,v|
        if Okvalue::FEED_SHOW_SIZE[k] < 1
          @feed_lists[k] = collectTextFeed(k)
        end
      end
      Style.image_feed.each do |k,v|
        if Okvalue::FEED_SHOW_SIZE[k] < 1
          @feed_lists[k],@image_feed_lists[k] = collectImageFeed(k)
        end
      end
    end
    @okpage = :p_home
    @user = User.new if !current_user
    @weather_au = Weather.weather_for_location(Common.today, Okvalue::AU, :Brisbane).first
    @weather_kr = Weather.weather_for_location(Common.today, Okvalue::KR, :seo).first
    @rates = Rate.rate_for()
    @qlinks = QuickLink.links
    @admin_notice = AdminNotice.current_notice.first
    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  # Ajax
  def topic_feed
    @okpage = :p_home
    @category = params[:c].to_sym
    if Style.topic_linkable?(@category)
      if Style.text_feed?(@category)
        @list = collectTextFeed(@category)
        return
      end
    end
    logger.debug("category: #{@category}")
    limit = TopFeedList::TOP_FEED_LIMIT_CATE[@category].presence || TopFeedList::TOP_FEED_LIMIT
    case @category
    when :p_new_posted
      @list = TopFeedList.feed_new(limit)
    when :p_new_images
      @images = HotFeedList.hot_feed_for(HotFeedList.what_key?(@category),limit)
      logger.debug("Images: #{@images.length}")
    when :p_most_viewed
      @list = HotFeedList.hot_feed_for(HotFeedList.what_key?(@category),limit)
    when :p_most_commented
      @list = HotFeedList.hot_feed_for(HotFeedList.what_key?(@category),limit)
    end
  end
  
  # Ajax
  def top_feed
    @okpage = :p_home
    @category = params[:c].to_sym
    if Style.text_feed?(@category)
      @list = collectTextFeed(@category)
    else
      @list,@image_list = collectImageFeed(@category)
    end
  end
  
  def current_weather
    @country = params[:c]
    weather = Weather.weather_for(Common.today, @country)
    logger.debug("weather: #{weather.size}")
    @weather_map = Common.new_orderd_hash
    weather.each do |w|
      logger.debug("weather: #{w.location}")
      @weather_map[w.location.to_sym] = w
    end
    logger.debug("@weather_map: #{@weather_map}")
    @dateOn = weather.first.forecast_for if weather.present?
  end

  def current_rate
    @rates = Rate.rate_for()
    @dateOn = Common.date_format_ymdhm(@rates.first.issuedOn) if @rates.present?
  end
  
  def admin_notice
    @admin_notices = AdminNotice.notice_history
  end

  private

  def collect_image_id(image_list)
    ids = image_list.collect {|feed| feed.id }
  end

end

app/helpers/homes_helper.rb
module HomesHelper
  
  def _bed_bath_garage(estate)
    html = image_tag("#{I18n.locale}/#{Style.page(:p_estate)}/icon_bed.gif") + " " + estate.bed.to_s + " " +
      image_tag("#{I18n.locale}/#{Style.page(:p_estate)}/icon_bath.gif") + " " + estate.bath.to_s + " " +
      image_tag("#{I18n.locale}/#{Style.page(:p_estate)}/icon_garage.gif") + " " + estate.garage.to_s 
  end
  
  def _scroll_feed(category, var_flag)
    return "" if !Style.feedable?(category)
    html = %Q|if ($(this).scrollTop() > #{Okvalue::FEED_SHOW_SIZE[category]}) {
      if(!#{var_flag}) {
        #{_show_feed(category)}
        #{var_flag} = true;
      }
    }|
    html.html_safe
  end

  def _show_feed(category) 
    params = %Q|c: '#{category}'|
    post_script = Ajax.post(top_feed_homes_path, params)
    html = %Q|$('\#feed_body_' + '#{category}').html("| + escape_javascript(image_tag("common/ajax_loading_1.gif")) + %Q|");|
    html += post_script
    html.html_safe
  end
  
  def topic_feed_div(category, id)
    html = %Q|<div class="row-fluid"><div class="btn-toolbar">|
    if Style.topic_linkable?(category)
      html += %Q|<div class="btn-group">| + link_to(t('more'), Okboard.okboard_link(category), :class => "btn btn-small") + "</div>"
      if Style.open_page?(category)
        html += %Q|<div class="btn-group"><a href="#{Okboard.okboard_link_write(category)}" class="btn btn-small"><i class="icon-pencil"></i>#{t(:write_new)}</a></div>|
      end
      sub_categories(category).each do |key,sub_category|
        html += %Q|<div class="btn-group"><a href="#{Okboard.okboard_link_with_category(category,sub_category)}" class="" ><span class="label label-info">#{t(sub_category)}</span></a></div>|
      end
    end
    html += %Q|</div><div class="row-fluid" id="#{id}"></div></div>|
    html.html_safe
  end
  
  def top_feed_div(category)
    return if !Style.feedable?(category)
    color = Okvalue::FEED_COLORMAP[category]
    lists = @feed_lists[category]
    image_list = @image_feed_lists[category]
    html = %Q|<div id="top_feed_list_#{category}" class="top_feed_list box_round white_box bs-docs">|
    html += %Q|<div id="feed_head" style="position:relative;width:100%;height:40px;background:#{Okvalue::COLORMAP[color]}"><div class="box_round" id="feed_head_left"><p class="" style="line-height: 40px;">#{t("#{Style.page(category)}")}</p></div>|
    html += %Q|<div id="feed_head_right"><p>| + link_to(t('more'), Okboard.okboard_link(category), :class => "btn btn-small") + " "
    if Style.open_page?(category)
      html += %Q|<a href="#{Okboard.okboard_link_write(category)}" class="btn btn-small"><i class="icon-pencil"></i>#{t(:write_new)}</a>|
    end
    html += %Q|</p></div></div><div id="feed_body_#{category}" class="feed_body">|
    if !top_page_ajaxable? || Okvalue::FEED_SHOW_SIZE[category] < 1
      html += generateTopFeed(category, lists, image_list)
    end
    html += "</div></div>"
    html.html_safe
  end
  
  def generateTopFeed(category, lists, image_list, length=nil, author=nil, views=nil, comment=nil)
    html = ""
    if Style.text_feed?(category) && !lists.present?
      html += %Q|<p>#{t("no_information")}</p>|
    elsif Style.image_feed?(category) && !lists.present? && !image_list.present?
      html += %Q|<p>#{t("no_information")}</p>|
    elsif !lists.present? && !image_list.present?
      html += %Q|<p>#{t("no_information")}</p>|
    else
      html = %Q|<table class="table table-hover table-condensed"><tr></tr>|
      if image_list.present?
         image_list.each do |feed|
           category = Style.m2s(feed.feeded_to_type)
           html += %Q|<tr><td width=40%><div class="shadow">|
           image = feed.feeded_to.image_feed_for
           if image.linkable?
             html += "#{link_to(image_tag(image.thumb_image, :class => "image-resize140_120"), image.link_to_url)}</div></td>"
           else
             html += "#{image_tag(image.thumb_image, :class => "image-resize140_120")}</div></td>"
           end
           html += %Q|<td align="left" valign="top">#{_truncate_with_length(feed.feeded_to.subject, 70)}|
           html += "<p>#{feed.feeded_to.postedDate}</p>"
           if feed.feeded_to.respond_to?(:price) && feed.feeded_to.price.present?
             html += %Q|<p class="price_tag">| + feed.feeded_to.price + "</p>"
           end
           if category.eql?(:p_estate)
             html +=  %Q|<div class="bed_bath_garage">| + _bed_bath_garage(feed.feeded_to) + "</div>"
           else
             html += "<p></p>"
           end
           html += %Q|<div class="feed_category_view">| + link_to(t(:view),"#",:class => "btn btn-mini btn-info disabled") + section_span_for(feed.feeded_to,category) + "</div>"
        end
        html += %Q|</table><table class="table table-striped table-hover table-condensed">|
      end
      lists.each_with_index do |feed,index|
        post = feed.respond_to?(:feeded_to)? feed.feeded_to : feed.hot_feeded_to
        Rails.logger.debug("feedpost: #{post}")
        category = Style.m2s(post.class.to_s)
        html += %Q|<tr>|
        html += %Q|<td style="height:20px;"><img src="assets/#{I18n.locale}/#{Style.page(@okpage)}/ic_arrow.gif"></td>|
        html += %Q|<td>#{link_to(_truncate_with_length(post.subject,length), Okboard.okboard_link_with_id(category, post.id), :class => "btn-link")}</td>|
        html += %Q|<td nowrap>#{t(post.category)}</td>|
        if author.present? && author
          html += %Q|<td><i class="icon-user"></i>&nbsp;#{author_name(post)}</td>|
        end
        html += %Q|<td nowrap>#{post.feeded_date}</td>|
        if views.present? && views
          html += %Q|<td>#{post.views}</td>|
        end
        if comment.present? && comment
          html += %Q|<td><i class="icon-comment"></i>&nbsp;#{post.comment.size}</td></tr>|
          html += %Q|<tr><td colspan="6"><blockquote><span class="topic-inline-comment">#{post.comment.last.body}</span><small><i class="icon-user"></i>&nbsp;#{comment_author(post.comment.last)}&nbsp;#{post.comment.last.feeded_date} </small></blockquote></td>|
        end
        html += "</tr>"
      end
      html += "</table>"
    end
   
    html.html_safe
  end
  
  def sub_categories(category)
    case category
    when :p_job
      categories = Job::Categories
    when :p_buy_and_sell
      categories = BuyAndSell::Categories
    when :p_well_being
      categories = WellBeing::Categories
    when :p_motor_vehicle
      categories = MotorVehicle::Categories
    when :p_estate
      categories = Estate::Categories
    when :p_business
      categories = Business::Categories
    when :p_accommodation
      categories = Accommodation::Categories
    when :p_law
      categories = Law::Categories
    when :p_tax
      categories = Tax::Categories
    when :p_study
      categories = Study::Categories
    when :p_immig
      categories = Immigration::Categories
    else
      raise Exceptions::BadRequestError
    end
    categories
  end
  
  def _sub_menu(link)
    categories = sub_categories(link)
    html = ""
    categories.each do |key,category|
      html += "<li><a href=\"#{Okboard.okboard_link_with_category(link,category)}\" tabindex=\"-1\">#{t(category)}</a></li>"
    end
    if Style.open_page?(link)
      html += "<li><a href=\"#{Okboard.okboard_link_write(link)}\" tabindex=\"-1\">#{t(:write_new)}</a></li>"
    end
    html.html_safe
  end
  
  
  def _path(links)
    path = Array.new
    links.each do |link|
      if link.eql?(:p_yellowpage)
        path.push(yellowpage_okboards_path)
      else
        path.push(Okboard.okboard_link(link))
      end
    end
    path
  end


end

app/views/homes/header/_admin_notice.html.erb
<div id="admin_notice">
	<a href="#adminNoticeModal" role="button" class="btn btn-link" data-toggle="modal" id="a_adminNoticeModal"><span class="label label-info"><i class="icon-info-sign icon-white"></i><%= t(:admin_notice)%></span></a>
	<div class="alert alert-info">
		<button type="button" class="close" data-dismiss="alert">
			×
		</button>
		<% if @admin_notice.present? %>
		<%= @admin_notice.subject %>
		<% else %>
		<%= t(:no_notice)%>
		<%end %>
	</div>
	<div class="modal hide fade" id="adminNoticeModal" tabindex="-1" role="dialog" aria-labelledby="adminNoticeLabel" aria-hidden="true">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
				×
			</button>
			<h3 id="adminNoticeLabel"><%= t(:admin_notice)%></h3>
		</div>
		<div class="modal-body" id="modal-body_admin_notice">
			<%= image_tag("common/ajax_loader_1.gif") %>
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal" aria-hidden="true">
				<%= t(:close)%>
			</button>
		</div>
		<%= _script(%Q|$('\#a_adminNoticeModal').click(function(){$.post('| + admin_notice_homes_path + %Q|');})|) %>
	</div>
</div>

app/views/homes/header/_header.html.erb
<ul class="thumbnails" style="margin-top:10px">
<li class="span7">
<div class="">
<% logo = BusinessClient.okbrisbane?.logo_for(Webcom::Browser::DEVISE_PC) %>
<% if logo.present? %>
<%= link_to image_tag(logo.original_image, :class => "img-rounded img-polaroid"), root_path(:locale => 'ko' ) %>
<% else %>
<%= link_to image_tag("http://placehold.it/330x180", :class => "img-rounded img-polaroid"), root_path(:locale => 'ko' ) %>
<% end %>
</div>
</li>
<li class="span5">
	<div class="row-fluid">
<% if !current_user %>
<%= form_for("user", :url => user_session_path, :html => { :class => "header-signin-form"}) do |f| %>
<div class="control-group">
	<div class="controls">
	<div class="input-prepend">
		<span class="add-on"><i class="icon-envelope"></i></span><%= f.email_field :email, :class => "input-large" %>
	</div>
	</div>
</div>
<div class="control-group">
	<div class="controls">
<div class="input-prepend">
	<span class="add-on"><i class="icon-key"></i></span><%= f.password_field :password, :class => "input-large" %>
</div>
</div>
</div>
<label class="checkbox"> <%= f.check_box :remember_me %><%= t(:remember_me_short) %> </label>
<%= link_to_with_icon(t(:signin), "#", "btn btn-primary", "", "icon-signin", "header-signin") %>
<span class="header-signin-progress"></span>
<%= link_to(t("findid_short"),new_user_confirmation_path,:class=>"")%>
<%= link_to(t("findpassword"),new_user_password_path,:class=>"")%>
<%= _document_on("click","\#header-signin",%Q|function(){
	$(".header-signin-form").submit();
	return false;
	}
|)
%>
<% end %>
<% else %>
<%= link_to_with_icon(t(:mypage), mypage_okboards_path, "btn", "", "icon-user") %>
<%= link_to_with_icon_with_method(t(:signout), destroy_user_session_path, "btn", "", "icon-signout", "", "delete") %>
<%= show_user %>
<% end %>
</div>
<div class="row-fluid">
		<% if !current_user %>

<%= pc_facebook %>&nbsp;
<%= pc_google %>&nbsp;
<%= link_to_with_icon(t(:signup), user_sign_up_path, "btn btn-link", "", "icon-ok") %>
<% else %>

<%= fb_shout %>
<% end %>

</li>
</ul>

app/views/homes/header/_navigation.html.erb
<ul class="nav nav-tabs box_round">
	<% Style.navi.each do |key| %>
	<% value = Style.page(key) %>
	<% link = key.eql?(:p_yellowpage) ? yellowpage_okboards_path : Okboard.okboard_link(key) %>
	<li class="dropdown" id="navi_<%= key%>">
		<a href="<%= link%>" class="dropdown-toggle ok-nav" data-toggle="" data-target="#"><i class="<%= Style.feed_icon(key)%>"></i>&nbsp;<%= t(value)%><b class="caret"></b></a>
		<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
			<%= _sub_menu(key)%>
		</ul>
	</li>
	<li class="divider-vertical"></li>
	<% end %>
	<li>
	<form class="">
				<div class="input-append">
					<span class="add-on"><i class="icon-search"></i></span>
					<input type="text" class="input-small" id="search-query" placeholder="<%= t(:search_keyword)%>"/>
					<button class="btn" type="button">
						<%= t(:search)%>
					</button>
				</div>
	</form>
	</li>
	<!--
	<li>
	<%= link_to_with_icon(t("bookmarkme"),"#","","","icon-bookmark icon-border","bookmarkme")%>
	</li>
	-->
</ul>
<!--
<%= _script_document_ready(%Q|
$('\#bookmarkme').click(function() {
var url = "#{root_url}";
var title = "QUEENSLAND PORTAL OKBRISBANE";
if (document.all) {// ie
window.external.AddFavorite(url, title);
} else if (window.sidebar) {// firefox
console.log("firefox")
window.sidebar.addPanel(title, url, "");
} else if (window.opera && window.print) {// opera
var elem = document.createElement('a');
elem.setAttribute('href', url);
elem.setAttribute('title', title);
elem.setAttribute('rel', 'sidebar');
elem.click();
// this.title=document.title;
}
});
|)
%>
-->